export const FETCH_LOCATION_BY_COORDINATES = 'FETCH-LOCATION-BY-COORDINATES';
export const FETCH_LOCATION_BY_ADDRESS = 'FETCH-LOCATION-BY-ADDRESS';
export const FETCH_CURRENT_WEATHER = 'FETCH-CURRENT-WEATHER';
export const FETCH_DAILY_WEATHER = 'FETCH-DAILY-WEATHER';
export const FETCH_HOURLY_WEATHER = 'FETCH-HOURLY-WEATHER';
